apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-nodejs-app
    app.kubernetes.io/part-of: e2e-nodejs
  name: single-nodejs-app
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: single-nodejs-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: single-nodejs-app
    spec:
      containers:
      - image: quay.io/ysubrama_org/e2e-demos-jogz-tenant/e2e-nodejs/single-nodejs-app@sha256:87a3990e56eb66502293115f6ad45838b8c02a9e7dae8bb3329b79478cc3b586
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
