apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-nodejs-app
    app.kubernetes.io/part-of: e2e-nodejs
  name: single-nodejs-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: single-nodejs-app
status:
  loadBalancer: {}
